第一個測試PR
superRainbow/vue3-admin pull request #4
Opened 2021-07-08 03:33 UTC by VincentChen1212

[測試] 新增API2
[測試] PR回饋後修正

2021-07-08 12:20 UTC, superRainbow requested changes
有再次給建議～

2021-07-09 03:57 UTC, VincentChen1212 commented on src/api/index.ts
> +import { getInvestorList } from './Investor/list';
這個已經修改成一個檔案

2021-07-09 06:01 UTC, VincentChen1212 commented on src/store/Investor/index.ts
> +      } finally {
已移除

2021-07-09 06:01 UTC, VincentChen1212 commented on src/store/Investor/index.ts
> +      } finally {
已移除

2021-07-09 06:33 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +import { computed, onBeforeMount, ref } from '@vue/runtime-core';
可以改成 'vue'
PS：'@vue/runtime-core' 是自動 import 的

2021-07-09 07:09 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +export default {
已新增 defineComponent

2021-07-09 07:24 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +<script>
已調整

2021-07-09 07:51 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +    @row-click.="handRowClick"
已移除

2021-07-09 07:51 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +      store.dispatch('investor/handDetail', id).then(() => {
這題PASS，不理他

2021-07-09 08:19 UTC, VincentChen1212 commented on src/views/Investor/list.vue
> +    const handRowClick = row => {
已調整

2021-07-09 10:14 UTC, superRainbow approved these changes
都沒有問題囉～～～～

2021-07-09 10:29 UTC, closed without merging